
module.exports={
        gamedata_link_urls:[
        {
            tg:'gm',
            ctx:'GM命令',
            result:'result',
            url:'/gamedata/item',
            uri:'/gamedata/result',
            proxy_path:'/gm',
            supercmd:false
        },
        {
            tg:'useronlines',
            ctx:'服务器在线人数',
            result:'result',
            url:'/gamedata/item',
            uri:'/gamedata/result',
            proxy_path:'/gm',
            supercmd:false
        },
        {
            tg:'iptable',
            ctx:'更新IP过滤表',
            result:'result',
            url:'/gamedata/item',
            uri:'/gamedata/result',
            proxy_path:'/fsm/cfg/iptable',
            supercmd:true
        },
        {
            tg:'tool_reload',
            ctx:'更新config.ini配置表',
            result:'result',
            url:'/gamedata/item',
            uri:'/gamedata/result',
            proxy_path:'/tool/reload',
            supercmd:true
        },
        {
            tg:'player_kick',
            ctx:'踢人',
            result:'result',
            url:'/gamedata/item',
            uri:'/gamedata/result',
            proxy_path:'/player/kick',
            supercmd:true
        },
        {
            tg:'player_privateIap',
            ctx:'私人定制礼包',
            result:'result',
            url:'/gamedata/item',
            uri:'/gamedata/result',
            proxy_path:'/player/privateIap',
            supercmd:true
        },
        {
            tg:'player_privateIap_reload',
            ctx:'私人定制礼包更新',
            result:'result',
            url:'/gamedata/item',
            uri:'/gamedata/result',
            proxy_path:'/player/privateIap/reload',
            supercmd:true
        },
        {
            tg:'player_privateIap_del',
            ctx:'私人定制礼包删除',
            result:'result',
            url:'/gamedata/item',
            uri:'/gamedata/result',
            proxy_path:'/player/privateIap/del',
            supercmd:true
        },
        {
            tg:'player_privateIap_list',
            ctx:'私人定制礼包列表',
            result:'result',
            url:'/gamedata/item',
            uri:'/gamedata/result',
            proxy_path:'/player/privateIap/list',
            supercmd:true
        },
        {
            tg:'tool_diamond',
            ctx:'玩家钻石修改',
            result:'result',
            url:'/gamedata/item',
            uri:'/gamedata/result',
            proxy_path:'/tool/diamond',
            supercmd:true
        },
        {
            tg:'users_maillist',
            ctx:'批量发送玩家邮件',
            result:'result',
            url:'/gamedata/item',
            uri:'/gamedata/result',
            proxy_path:'/users/maillist',
            supercmd:true
        },
        {
            tg:'players_playersMail',
            ctx:'批量发送玩家模板邮件',
            result:'result',
            url:'/gamedata/item',
            uri:'/gamedata/result',
            proxy_path:'/players/playersMail',
            supercmd:true
        },
        {
            tg:'player_mail',
            ctx:'发送玩家邮件',
            result:'result',
            url:'/gamedata/item',
            uri:'/gamedata/result',
            proxy_path:'/player/mail',
            supercmd:true
        },
        {
            tg:'player_update_money',
            ctx:'修改玩家钻石',
            result:'result',
            url:'/gamedata/item',
            uri:'/gamedata/result',
            proxy_path:'/player/update_money',
            supercmd:true
        },
        {
            tg:'templates_new',
            ctx:'创建多语言模板',
            result:'result',
            url:'/gamedata/item',
            uri:'/gamedata/result',
            proxy_path:'/templates/new',
            supercmd:true
        },
        {
            tg:'templates_update',
            ctx:'修改多语言模板',
            result:'result',
            url:'/gamedata/item',
            uri:'/gamedata/result',
            proxy_path:'/templates/update',
            supercmd:true
        },
        {
            tg:'templates_del',
            ctx:'删除多语言模板',
            result:'result',
            url:'/gamedata/item',
            uri:'/gamedata/result',
            proxy_path:'/templates/del',
            supercmd:true
        },
        {
            tg:'templates_get',
            ctx:'查询多语言模板',
            result:'result',
            url:'/gamedata/item',
            uri:'/gamedata/result',
            proxy_path:'/templates/get',
            supercmd:true
        },
        {
            tg:'templates_sync',
            ctx:'多语言模板同步',
            result:'result',
            url:'/gamedata/item',
            uri:'/gamedata/result',
            proxy_path:'/templates/sync',
            supercmd:true
        },
        {
            tg:'common_sync',
            ctx:'多语言文本同步',
            result:'result',
            url:'/gamedata/item',
            uri:'/gamedata/result',
            proxy_path:'/common/sync',
            supercmd:true
        },
        {
            tg:'common_new',
            ctx:'多语言文本新建',
            result:'result',
            url:'/gamedata/item',
            uri:'/gamedata/result',
            proxy_path:'/common/new',
            supercmd:true
        },
        {
            tg:'common_update',
            ctx:'多语言文本修改',
            result:'result',
            url:'/gamedata/item',
            uri:'/gamedata/result',
            proxy_path:'/common/update',
            supercmd:true
        },
        {
            tg:'common_del',
            ctx:'多语言文本删除',
            result:'result',
            url:'/gamedata/item',
            uri:'/gamedata/result',
            proxy_path:'/common/del',
            supercmd:true
        },
        {
            tg:'common_get',
            ctx:'多语言文本获取',
            result:'result',
            url:'/gamedata/item',
            uri:'/gamedata/result',
            proxy_path:'/common/get',
            supercmd:true
        },
        {
            tg:'huodong_save',
            ctx:'活动创建',
            result:'result',
            url:'/gamedata/item',
            uri:'/gamedata/result',
            proxy_path:'/huodong/save',
            supercmd:true
        },
        {
            tg:'huodong_get',
            ctx:'活动获取',
            result:'result',
            url:'/gamedata/item',
            uri:'/gamedata/result',
            proxy_path:'/huodong/get',
            supercmd:true
        },
        {
            tg:'huodong_revoke',
            ctx:'活动删除',
            result:'result',
            url:'/gamedata/item',
            uri:'/gamedata/result',
            proxy_path:'/huodong/revoke',
            supercmd:true
        },
        {
            tg:'huodong_deploy',
            ctx:'活动上线',
            result:'result',
            url:'/gamedata/item',
            uri:'/gamedata/result',
            proxy_path:'/huodong/deploy',
            supercmd:true
        },
        {
            tg:'huodong_destroy',
            ctx:'活动下线',
            result:'result',
            url:'/gamedata/item',
            uri:'/gamedata/result',
            proxy_path:'/huodong/destroy',
            supercmd:true
        },
        {
            tg:'huodong_rankrewards',
            ctx:'活动排行奖励查询',
            result:'result',
            url:'/gamedata/item',
            uri:'/gamedata/result',
            proxy_path:'/huodong/rankrewards',
            supercmd:true
        },
        {
            tg:'huodong_huodong',
            ctx:'活动查询',
            result:'result',
            url:'/gamedata/item',
            uri:'/gamedata/result',
            proxy_path:'/huodong/huodong',
            supercmd:true
        },
        {
            tg:'huodong_config_kind',
            ctx:'活动kind查询',
            result:'result',
            url:'/gamedata/item',
            uri:'/gamedata/result',
            proxy_path:'/huodong/config/kind',
            supercmd:true
        },
        {
            tg:'huodong_calcurewards',
            ctx:'活动奖励计算查询',
            result:'result',
            url:'/gamedata/item',
            uri:'/gamedata/result',
            proxy_path:'/huodong/calcurewards',
            supercmd:true
        },
        {
            tg:'huodong_addmult',
            ctx:'活动草稿添加',
            result:'result',
            url:'/gamedata/item',
            uri:'/gamedata/result',
            proxy_path:'/huodong/addmult',
            supercmd:true
        },
        {
            tg:'huodong_batch_deploy',
            ctx:'活动批量上线',
            result:'result',
            url:'/gamedata/item',
            uri:'/gamedata/result',
            proxy_path:'/huodong/batch/deploy',
            supercmd:true
        },
        {
            tg:'huodong_batch_destroy',
            ctx:'活动批量下线',
            result:'result',
            url:'/gamedata/item',
            uri:'/gamedata/result',
            proxy_path:'/huodong/batch/destroy',
            supercmd:true
        },
        {
            tg:'server_mail',
            ctx:'全服发送邮件',
            result:'result',
            url:'/gamedata/item',
            uri:'/gamedata/result',
            proxy_path:'/server/mail',
            supercmd:true
        },
        {
            tg:'server_mails',
            ctx:'gs发送系统邮件',
            result:'result',
            url:'/gamedata/item',
            uri:'/gamedata/result',
            proxy_path:'/server/mails',
            supercmd:true
        },
        {
            tg:'announce_online',
            ctx:'系统公告添加',
            result:'result',
            url:'/gamedata/item',
            uri:'/gamedata/result',
            proxy_path:'/announce/online',
            supercmd:true
        },
        {
            tg:'system_iapcontrol',
            ctx:'IAP礼包上下线控制',
            result:'result',
            url:'/gamedata/item',
            uri:'/gamedata/result',
            proxy_path:'/system/iapcontrol',
            supercmd:true
        },
        {
            tg:'tool_item',
            ctx:'玩家道具修改',
            result:'result',
            url:'/gamedata/item',
            uri:'/gamedata/result',
            proxy_path:'/tool/item',
            supercmd:false
        },
        {
            tg:'tool_equipment',
            ctx:'玩家装备添加',
            result:'result',
            url:'/gamedata/item',
            uri:'/gamedata/result',
            proxy_path:'/tool/equipment',
            supercmd:false
        },
        {
            tg:'tool_troop',
            ctx:'玩家部队修改',
            result:'result',
            url:'/gamedata/item',
            uri:'/gamedata/result',
            proxy_path:'/tool/troop',
            supercmd:false
        },
        {
            tg:'users_mail',
            ctx:'发送玩家邮件',
            result:'result',
            url:'/gamedata/item',
            uri:'/gamedata/result',
            proxy_path:'/users/mail',
            supercmd:false
        },
        {
            tg:'players',
            ctx:'查询玩家角色名或ID',
            result:'result',
            url:'/gamedata/item',
            uri:'/gamedata/result',
            proxy_path:'/players',
            supercmd:false
        },
        {
            tg:'player',
            ctx:'查询玩家信息',
            result:'player_result',
            url:'/gamedata/item',
            uri:'/gamedata/result',
            proxy_path:'/player',
            supercmd:false
        },
        {
            tg:'player_items',
            ctx:'查询玩家包裹',
            result:'items_result',
            url:'/gamedata/item',
            uri:'/gamedata/result',
            proxy_path:'/player/items',
            supercmd:false
        },
        {
            tg:'player_resources',
            ctx:'查询玩家资源',
            result:'result',
            url:'/gamedata/item',
            uri:'/gamedata/result',
            proxy_path:'/player/resources',
            supercmd:false
        },
        {
            tg:'player_update_items',
            ctx:'修改玩家道具',
            result:'result',
            url:'/gamedata/item',
            uri:'/gamedata/result',
            proxy_path:'/player/update_items',
            supercmd:false
        },
        {
            tg:'player_update_resources',
            ctx:'修改玩家资源',
            result:'result',
            url:'/gamedata/item',
            uri:'/gamedata/result',
            proxy_path:'/player/update_resources',
            supercmd:false
        },
        {
            tg:'player_armies',
            ctx:'玩家部队信息',
            result:'result',
            url:'/gamedata/item',
            uri:'/gamedata/result',
            proxy_path:'/player/armies',
            supercmd:false
        },
        {
            tg:'player_garrisons',
            ctx:'玩家城防部队信息',
            result:'result',
            url:'/gamedata/item',
            uri:'/gamedata/result',
            proxy_path:'/player/garrisons',
            supercmd:false
        },
        {
            tg:'player_update_armies',
            ctx:'修改玩家兵种数量',
            result:'result',
            url:'/gamedata/item',
            uri:'/gamedata/result',
            proxy_path:'/player/update_armies',
            supercmd:false
        },
        {
            tg:'player_mapinfo',
            ctx:'玩家野外部队信息',
            result:'result',
            url:'/gamedata/item',
            uri:'/gamedata/result',
            proxy_path:'/player/mapinfo',
            supercmd:false
        },
        {
            tg:'player_shield',
            ctx:'玩家添加系统护盾',
            result:'result',
            url:'/gamedata/item',
            uri:'/gamedata/result',
            proxy_path:'/player/shield',
            supercmd:false
        },
        {
            tg:'player_account_data',
            ctx:'玩家账号信息',
            result:'result',
            url:'/gamedata/item',
            uri:'/gamedata/result',
            proxy_path:'/player/account_data',
            supercmd:false
        },
    ],
	gamelog_link_urls:[
        {
            tg:'players_power',
            ctx:'新增账号战力列表',
            result:'players_power_result',
            url:'/gamelog/item',
            uri:'/gamelog/result',
            proxy_path:'players_power',
            supercmd:false
        },
        {
            tg:'user_register_logs',
            ctx:'查询玩家注册信息',
            result:'user_register_logs_result',
            url:'/gamelog/item',
            uri:'/gamelog/result',
            proxy_path:'user_register_logs',
            supercmd:false
        },
        {
            tg:'user_login_logs',
            ctx:'查询玩家登录信息',
            result:'user_login_logs_result',
            url:'/gamelog/item',
            uri:'/gamelog/result',
            proxy_path:'user_login_logs',
            supercmd:false
        },
        {
            tg:'user_gather',
            ctx:'查询玩家采集信息',
            result:'user_gather_result',
            url:'/gamelog/item',
            uri:'/gamelog/result',
            proxy_path:'user_gather',
            supercmd:false
        },
        {
            tg:'user_retention',
            ctx:'玩家单日留存查询',
            result:'user_retention_result',
            url:'/gamelog/item',
            uri:'/gamelog/result',
            proxy_path:'user_retention',
            supercmd:false
        },
        {
            tg:'user_retentions',
            ctx:'玩家多日留存查询',
            result:'user_retentions_result',
            url:'/gamelog/item',
            uri:'/gamelog/result',
            proxy_path:'user_retentions',
            supercmd:false
        },
        {
            tg:'user_device',
            ctx:'查询玩家设备信息',
            result:'user_device_result',
            url:'/gamelog/item',
            uri:'/gamelog/result',
            proxy_path:'user_device',
            supercmd:false
        },
        {
            tg:'chat_alliance',
            ctx:'公会聊天记录查询',
            result:'chat_alliance_result',
            url:'/gamelog/item',
            uri:'/gamelog/result',
            proxy_path:'chat_alliance',
            supercmd:false
        },
        {
            tg:'user_rebel',
            ctx:'玩家打怪行为明细',
            result:'user_rebel_result',
            url:'/gamelog/item',
            uri:'/gamelog/result',
            proxy_path:'user_rebel',
            supercmd:false
        },
        {
            tg:'regionall',
            ctx:'各个地区留存统计',
            result:'regionall_result',
            url:'/gamelog/item',
            uri:'/gamelog/result',
            proxy_path:'regionall',
            supercmd:false
        },
        {
            tg:'google_pay',
            ctx:'礼包购买查询',
            result:'google_pay_result',
            url:'/gamelog/item',
            uri:'/gamelog/result',
            proxy_path:'google_pay',
            supercmd:false
        },
        {
            tg:'google_pay1',
            ctx:'',
            result:'google_pay1_result',
            url:'/gamelog/item',
            uri:'/gamelog/result',
            proxy_path:'google_pay1',
            supercmd:false
        },
        {
            tg:'google_pay2',
            ctx:'礼包购买统计',
            result:'google_pay2_result',
            url:'/gamelog/item',
            uri:'/gamelog/result',
            proxy_path:'google_pay2',
            supercmd:false
        },
        {
            tg:'gm_cmd',
            ctx:'礼包内购查询',
            result:'gm_cmd_result',
            url:'/gamelog/item',
            uri:'/gamelog/result',
            proxy_path:'gm_cmd',
            supercmd:false
        },
        {
            tg:'chargeRank',
            ctx:'',
            result:'chargeRank_result',
            url:'/gamelog/item',
            uri:'/gamelog/result',
            proxy_path:'chargeRank',
            supercmd:false
        },
        {
            tg:'user_information',
            ctx:'玩家信息查询',
            result:'user_information_result',
            url:'/gamelog/item',
            uri:'/gamelog/result',
            proxy_path:'user_information',
            supercmd:false
        },
        {
            tg:'user_behavior',
            ctx:'查询玩家行为',
            result:'user_behavior_result',
            url:'/gamelog/item',
            uri:'/gamelog/result',
            proxy_path:'user_behavior',
            supercmd:false
        },
        {
            tg:'user_str',
            ctx:'玩家流失统计',
            result:'user_str_result',
            url:'/gamelog/item',
            uri:'/gamelog/result',
            proxy_path:'user_str',
            supercmd:false
        },
        {
            tg:'user_equip',
            ctx:'查看玩家装备',
            result:'user_equip_result',
            url:'/gamelog/item',
            uri:'/gamelog/result',
            proxy_path:'user_equip',
            supercmd:false
        },
        {
            tg:'mongolog_alliance',
            ctx:'查询工会ID',
            result:'mongolog_alliance_result',
            url:'/gamelog/item',
            uri:'/gamelog/result',
            proxy_path:'mongolog_alliance',
            supercmd:false
        },
        {
            tg:'aoegmtool_users',
            ctx:'查询管理员',
            result:'aoegmtool_users_result',
            url:'/gamelog/item',
            uri:'/gamelog/result',
            proxy_path:'aoegmtool_users',
            supercmd:false
        },
        {
            tg:'delete_gmuser',
            ctx:'',
            result:'aoegmtool_users_result',
            url:'/gamelog/item',
            uri:'/gamelog/result',
            proxy_path:'delete_gmuser',
            supercmd:false
        },
        {
            tg:'count_behavior',
            ctx:'',
            result:'count_behavior_result',
            url:'/gamelog/item',
            uri:'/gamelog/result',
            proxy_path:'count_behavior',
            supercmd:false
        },
        {
            tg:'user_all',
            ctx:'',
            result:'user_all_result',
            url:'/gamelog/item',
            uri:'/gamelog/result',
            proxy_path:'user_all',
            supercmd:false
        },
        {
            tg:'user_allUTC',
            ctx:'综合查询',
            result:'user_allUTC_result',
            url:'/gamelog/item',
            uri:'/gamelog/result',
            proxy_path:'user_allUTC',
            supercmd:false
        },
        {
            tg:'user_allPST',
            ctx:'',
            result:'user_allPST_result',
            url:'/gamelog/item',
            uri:'/gamelog/result',
            proxy_path:'user_allPST',
            supercmd:false
        },
        {
            tg:'mail_password',
            ctx:'找回密码',
            result:'mail_password_result',
            url:'/gamelog/item',
            uri:'/gamelog/result',
            proxy_path:'mail_password',
            supercmd:false
        },
        {
            tg:'count_rebel',
            ctx:'',
            result:'count_rebel_result',
            url:'/gamelog/item',
            uri:'/gamelog/result',
            proxy_path:'count_rebel',
            supercmd:false
        },
        {
            tg:'user_shield',
            ctx:'玩家防护罩剩余时间查询',
            result:'user_shield_result',
            url:'/gamelog/item',
            uri:'/gamelog/result',
            proxy_path:'user_shield',
            supercmd:false
        },
        {
            tg:'registertoorder',
            ctx:'LTV',
            result:'registertoorder_result',
            url:'/gamelog/item',
            uri:'/gamelog/result',
            proxy_path:'registertoorder',
            supercmd:false
        },
        {
            tg:'jc',
            ctx:'推送',
            result:'jc_result',
            url:'/gamelog/item',
            uri:'/gamelog/result',
            proxy_path:'jc',
            supercmd:false
        },
        {
            tg:'test1',
            ctx:'查询推送操作以及结果',
            result:'test1_result',
            url:'/gamelog/item',
            uri:'/gamelog/result',
            proxy_path:'test1',
            supercmd:false
        },
        {
            tg:'bootfour',
            ctx:'BOOT四步查询',
            result:'bootfour_result',
            url:'/gamelog/item',
            uri:'/gamelog/result',
            proxy_path:'bootfour',
            supercmd:false
        },
        {
            tg:'test',
            ctx:'',
            result:'test_result',
            url:'/gamelog/item',
            uri:'/gamelog/result',
            proxy_path:'test',
            supercmd:false
        },
        {
            tg:'bootversionip',
            ctx:'BOOT版本查询ip',
            result:'bootversionip_result',
            url:'/gamelog/item',
            uri:'/gamelog/result',
            proxy_path:'bootversionip',
            supercmd:false
        },
    ]
}